### ISSUE TITLE
final checklist

### ISSUE THREAD

**Issue by colleenmcguckin** [colleenmcguckin/travel_behavior#36]
- [ ] use proper email address for contact inquiries
- [ ] update admin instruction panel
- [ ] remove dead code
- [ ] use proper email address to login to admin panel
- [ ] link to admin panel somewhere
- [ ] link up all PDFs
- [ ] switch domain over
- [ ] ssl certificate
- [ ] click every link
